kiyoyuki.fujii Exercise
accel194/elites-crm02 pull request #1
Opened 2016-12-09 10:27 UTC by accel194

2016-12-09 15:58 UTC, kazu-taka commented on app/controllers/customers_controller.rb
> +    redirect_to @customer
インデントの確認をお願いします

2016-12-09 15:59 UTC, kazu-taka commented on app/controllers/customers_controller.rb
> +    @customer = Customer.find(params[:id])
インデントの確認をお願いします。

2016-12-09 16:02 UTC, kazu-taka commented on app/models/customer.rb
> +    end
上記の3行は半角スペース2文字分左に移動(アウトデント)お願いします。

2016-12-09 16:03 UTC, kazu-taka commented on app/views/customers/show.html.erb
>          <h1>顧客詳細</h1>
htmlのインデントも半角スペース2文字で統一お願いします。

2016-12-09 16:03 UTC, kazu-taka commented on app/views/customers/show.html.erb
> +    　<h2>対応履歴</h2>
h2の開始を上記のhrに併せて下さい。

2016-12-09 16:05 UTC, kazu-taka commented on app/views/devise/registrations/new.html.erb
> +    <%= devise_error_messages! %>
このへんもインデントの確認をお願いします！

2016-12-09 16:06 UTC, kazu-taka commented on config/locales/ja.yml
> +
不要な空白行の削除をお願いします。

2016-12-09 16:13 UTC, kazu-taka commented on app/views/customers/show.html.erb
> +              <p><b><%= @comment.errors.count %>件のエラーがあります</br>・ Bodyは２００文字以内で入力してください</b></p>
エラーメッセージをHTMLに直接書くのは辞めましょう。
他のバリデーションを追加した際に関係ないエラーメッセージが表示されてしまうので。

2016-12-09 16:15 UTC, kazu-taka commented on app/views/customers/show.html.erb
> +                  <% @comment.errors.full_messages.each do |message| %>
ここにエラーメッセージを表示する処理を追記します。
参考リンクです。
http://ruby-rails.hatenadiary.com/entry/20140810/1407623400#view-validation

2016-12-09 16:20 UTC, kazu-taka commented
masterのコミット履歴を見ましたが、直近のコミット履歴が「create　error」となっているようです。
正常に動く状態でmasterブランチでコミットして頂きたかったです。
https://github.com/accel194/elites-crm02/commits/master

05_実習で作成したログイン機能等もexerciseブランチに含まれてしまっているようです。
今回はこのままでOKですが、次回の課題からは実習は全てmasterブランチで行うようにして下さい:smile:

上記にコメントしましたので、修正お願いします。

2016-12-16 12:30 UTC, kazu-taka commented on app/controllers/comments_controller.rb
> +
上記のような不要なコメントは削除しましょう:smile:

2016-12-16 12:30 UTC, kazu-taka commented on app/models/comment.rb
> +
バリデーションは一つの括りにして良いので、不要な空行は削除した方が良いですね:sparkles:
最初はどこの空行を削除するか分かりづらいと思いますが、その都度指摘しますので、感覚を掴むまでは一緒にやっていきましょう！！

2016-12-16 12:30 UTC, kazu-taka commented on app/models/customer.rb
>  end
インデントもいい感じですね:+1:

2016-12-16 12:30 UTC, kazu-taka commented on app/views/customers/index.html.erb
> +          </div>
上記の`<div>〜</div>`は上の`<div>〜</div>`の同じ並びになるので、インデントの確認をお願いします！

2016-12-16 12:30 UTC, kazu-taka commented on app/views/customers/index.html.erb
> +            <%= link_to "リセット", request.path, class:"btn btn-default" %>
こちらもインデントの確認お願いします！

2016-12-16 12:30 UTC, kazu-taka commented on app/views/customers/index.html.erb
>  </div>
一旦`app/views/customers/index.html.erb`の全てのインデントの確認をお願いします:bow:

2016-12-16 12:30 UTC, kazu-taka commented on app/views/customers/show.html.erb
> +          <% @comment.errors.full_messages.each do |comment| %>
上記に残っている私が書いたコメントも全て削除お願いします:bow:

2016-12-16 12:32 UTC, kazu-taka commented
@accel194 
レビュー完了しました！
機能的にはバッチリだと思いますので、不要な空行やインデントの修正だけお願いします:pray:
修正後に問題なければマージします:sparkles:
この調子も次も頑張りましょう！！

2016-12-16 12:34 UTC, accel194 commented
了解しました。　有難うございました。

2016-12-16 14:57 UTC, kazu-taka commented
@accel194 
まだいつくか修正点が残っておりましたので確認お願いします。
時間がかかってもいいので、じっくり確認お願いします:smile:

2016-12-16 15:02 UTC, kazu-taka requested changes

2016-12-16 15:02 UTC, kazu-taka commented on app/views/customers/index.html.erb
> +      <div class="row">
`<%= search_form_for @q do |f| %>`から`<% end %>`までが一つのセクションになるので、次の`<div class="row">`以降をインデントの確認をお願いします。(半角スペース2文字分中に入ります。)

2016-12-16 15:02 UTC, kazu-taka commented on app/views/customers/index.html.erb
> +      <div class="col-sm-2 col-xs-12">
上記の`<div class="col-sm-2 col-xs-12">`も上の`</div>`と揃う気がしますので、確認お願いします:bow:

2016-12-16 15:02 UTC, kazu-taka commented on app/views/customers/index.html.erb
> +    <hr />
上記の`<% end %>`は`<hr />`と揃う気がするので確認お願いします:bow:

2016-12-16 15:02 UTC, kazu-taka commented on app/views/customers/show.html.erb
>  <!-- commenという変数は存在しません -->
ここは修正前の状態が正しいです。
`</div>`を修正後のように改行してもいいですが、その場合でも`<ul>`を中に入れる必要はありません:bow:
`</div>`で終わっているので、`<ul>`も同じ位置から開始します！

2016-12-16 15:02 UTC, kazu-taka commented on app/views/customers/show.html.erb
>  <!-- commentという変数は存在しません -->
上記にも数行コメントが残っているので、削除お願いします:bow:

2016-12-17 12:12 UTC, kazu-taka approved these changes

2016-12-17 12:25 UTC, kazu-taka commented
@accel194 
問題ありませんでした！！バッチリです！！
次回もpushする前にインデントの確認お願いします:bow:
ではマージします！！

2016-12-17 12:25 UTC, merged